let x= 5
console.log(x==5);  // true
console.log(x===5);  // true
console.log(x!=5);  // false
console.log(x>3);   // true
console.log(x<3);   // false
console.log(x>=5);  // true
console.log(x<=3);  // false
console.log(x<=10);   // true
console.log(x>=10);  // false