let x=10;
console.log(x>5 && x<15);  // true (both conditions true)
console.log(x>5 || x<5);    // true (first condition true)
console.log(!(x>5));  // false (negation of true is false)
console.log(!(x<5));  // true (negation of false is true)
console.log(x>5 && x<10);  // false (second condition false)
console.log(x>5 || x<10);  // true (first condition true)
console.log(x>15 || x<5);  // false (both conditions false)
console.log(x>15 && x<5);  // false (both conditions false) 
console.log(!(x>15 || x<5));  // true (negation of false is true)
console.log(!(x>5 && x<15));  // false (negation of true is false)
console.log(!(x>5 || x<15));  // false (negation of true is false)
console.log(!(x>5 && x<10));  // true (negation of false is true)
console.log(!(x>5 || x<10));  // false (negation of true is false)
console.log(!(x>10 || x<10));  // true (negation of false is true)