let s= "Hii";
console.log(s + " there!");  // Hii there! (string concatenation)
console.log(s + " " + "How are you?");  // Hii How are you? (string concatenation with space)
console.log(s.length);  // 3 (length of the string)
console.log(s.toUpperCase());  // HII (convert to uppercase)
console.log(s.toLowerCase());  // hii (convert to lowercase)
console.log(s.charAt(0));  // H (character at index 0)
console.log(s.charAt(1));  // i (character at index 1)
console.log(s.charAt(2));  // i (character at index 2)
console.log(s.charAt(3));  // (empty string, index out of range)
console.log(s.indexOf("i"));  // 1 (index of first occurrence of "i")
console.log(s.indexOf("x"));  // -1 (not found)
console.log(s.substring(0, 2));  // Hi (substring from index 0 to 2)
console.log(s.substring(1));  // ii (substring from index 1 to end)
console.log(s.includes("H"));  // true (string contains "H")
console.log(s.includes("x"));  // false (string does not contain "x")           
